"""Add user preferences table

Revision ID: 59ea38b8a9c3
Revises: c9a31068e8cc
Create Date: 2026-09-23 15:31:23.169487

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59ea38b8a9c3'
down_revision = 'c9a31068e8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpreference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_workout_duration', sa.Integer(), nullable=False),
    sa.Column('workouts_per_week', sa.Integer(), nullable=False),
    sa.Column('available_equipment', sa.JSON(), nullable=False),
    sa.Column('workout_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpreference_user_id'), 'userpreference', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userpreference_user_id'), table_name='userpreference')
    op.drop_table('userpreference')
    # ### end Alembic commands ###
