"""add food logs table

Revision ID: 5be6eec9d87a
Revises: 3877cc4bbec9
Create Date: 2026-09-25 17:33:39.315610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5be6eec9d87a'
down_revision = '3877cc4bbec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('food_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('entry_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_detected_items', sa.JSON(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodlog_user_id'), 'foodlog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foodlog_user_id'), table_name='foodlog')
    op.drop_table('foodlog')
    # ### end Alembic commands ###
