"""expand recipe with nutrition

Revision ID: 959a1168f860
Revises: 8b78ccc1b8b2
Create Date: 2026-09-25 22:00:22.465245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '959a1168f860'
down_revision = '8b78ccc1b8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('ingredients', sa.JSON(), nullable=True))
    op.add_column('recipe', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipe', sa.Column('total_calories', sa.Float(), nullable=True))
    op.add_column('recipe', sa.Column('total_protein_g', sa.Float(), nullable=True))
    op.add_column('recipe', sa.Column('total_carbs_g', sa.Float(), nullable=True))
    op.add_column('recipe', sa.Column('total_fat_g', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'total_fat_g')
    op.drop_column('recipe', 'total_carbs_g')
    op.drop_column('recipe', 'total_protein_g')
    op.drop_column('recipe', 'total_calories')
    op.drop_column('recipe', 'instructions')
    op.drop_column('recipe', 'ingredients')
    # ### end Alembic commands ###
